### ISSUE TITLE
about.html question

### ISSUE THREAD

**Issue by realsidney** [klugjo/hexo-theme-anodyne#1]
i create an about.html file in public folder , and it works , but after [hexo clean] ,it disappear, how to solve it, thanks.

**Comment by klugjo** [comment]
This is a hexo related question, and has nothing to do with this theme but here you go:

`hexo clean` will clean up the whole public folder.

If you want to add a static page to your site, use the following command

`hexo new page about`

this will create an about.md file where you can put the content of your page and will be generated at the same time as the rest of your site

https://hexo.io/docs/writing.html

If you need a completely custom html file for your about.html, you can simply put it in the source folder instead, and it will be copied and updated in the public folder each time you generate your site.

**Comment by realsidney** [comment]
I am a new guy, and thanks your patient answer.

**Comment by klugjo** [comment]
No worries, if you continue playing around with hexo, you will quickly understand how it works.

Have fun
