### ISSUE TITLE
the main index.html is empty but the sub tags index.html is normal

### ISSUE THREAD

**Issue by giswt** [klugjo/hexo-theme-anodyne#3]
when I add tags   the index.html of the sub folder is normal.But the main tags' index.html can not be generated successfully. It is empty

**Comment by klugjo** [comment]
By default this index is not generated by Hexo. I can work something out though but I am really busy at the moment. Will take a week or two.

**Comment by jeanboydev** [comment]
@klugjo This theme is very beautiful, but I encountered the same problem. How long can you fix it?

**Comment by klugjo** [comment]
Sorry this took so long, I have pushed the changes:

Demo: http://www.codeblocq.com/assets/projects/hexo-theme-anodyne/
Instructions: https://github.com/klugjo/hexo-theme-anodyne#tags-page
