### ISSUE TITLE
I want to use the icon...

### ISSUE THREAD

**Issue by appear** [klugjo/hexo-theme-anodyne#4]
Hello :) I'm a developer from South Korea, I am using your theme
By the way, I have a two problems 

1. I want to use the icon but I do not know the name of the icon.  if you have a document with the name of the icon, Please tell me 

2. I want to use /about.html, but who should I follow the path?

Thank you have a nice day ~ :)

**Comment by klugjo** [comment]
1. The icons are Font Awesome icons: http://fontawesome.io/icons/

You need to use the css class, for example for the icon http://fontawesome.io/icon/address-book/, you should use `icon: fa-address-book`

2. For about.html, simply create a `about.md` file inside the `source` folder and put the following code inside:

```
title: About
date: 2013-12-26 22:52:56
icon: fa-info-circle
---

This is a page test. Not a normal post. Pages do not have comments or widgets. They do support icons and dates though.
```
