### ISSUE TITLE
hi folks, i wish to use devicon

### ISSUE THREAD

**Issue by extJo** [klugjo/hexo-theme-anodyne#5]
how can i do this...?

klugjo's blog is using devicon, but i don't understand how to apply devicon

**Comment by klugjo** [comment]
You need to modify the theme for that. 

- Remove the `fa` here: https://github.com/klugjo/hexo-theme-anodyne/blob/master/layout/_partial/article-short.ejs#L21

This is basically the place where the `icon` from your posts meta data will be used.

Do the same here as well for the details page: https://github.com/klugjo/hexo-theme-anodyne/blob/master/layout/_partial/banner.ejs#L29

- Then in the `head.ejs` you can add or replace font awesome with whatever you need: https://github.com/klugjo/hexo-theme-anodyne/blob/master/layout/_partial/head.ejs#L78

Hope that helps
