### ISSUE TITLE
How can I use other comment systems?

### ISSUE THREAD

**Issue by Azuelle** [klugjo/hexo-theme-anodyne#6]
I live in mainland China and Disqus is currently blocked here. So how can I change the comment system used in the theme, for example, to [Gitment](https://github.com/imsun/gitment)?

**Comment by klugjo** [comment]
I have no experience with gitment so you will have to implement it yourself. You can have a loot at

https://github.com/klugjo/hexo-theme-anodyne/blob/master/layout/_partial/comments.ejs

Modify that file to fit the gitment requirements

**Comment by Azuelle** [comment]
Thanks!
