### ISSUE TITLE
Wondering tags rendering

### ISSUE THREAD

**Issue by beanbroker** [klugjo/hexo-theme-anodyne#9]
Hello! I am happy to start my hexo blog by yours.

now, I am wondering How I can generate tags page like yours "http://www.codeblocq.com/assets/projects/hexo-theme-anodyne/tags/" 

I already made tags.md. ($ hexo new page "tags") and I checked _config.yml which has tags.

Should I make a tags.ejs??

Thanks for your sharing.

**Comment by klugjo** [comment]
Since you have closed this, I am guessing you have found the solution by yourself.

If not the explanations are here: https://github.com/klugjo/hexo-theme-anodyne#tags-page

Thanks for using my theme !
